update public.beallitasok
set
  site_name = 'FuvarVelünk',
  company_name = 'FuvarVelünk',
  contact_email = 'cegweb26@gmail.com',
  admin_email = 'cegweb26@gmail.com'
where id = 1;

alter table if exists public.fuvarok add column if not exists user_id uuid;
alter table if exists public.fuvarok add column if not exists approved boolean default false;
alter table if exists public.fuvarok add column if not exists created_at timestamptz default now();
alter table if exists public.fuvarok add column if not exists updated_at timestamptz default now();

create index if not exists idx_fuvarok_approved_created_at
on public.fuvarok (approved, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='fuvarok' and policyname='Fuvar beszúrás engedélyezése'
  ) then
    create policy "Fuvar beszúrás engedélyezése"
    on public.fuvarok
    for insert
    to authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='fuvarok' and policyname='Fuvar olvasás engedélyezése'
  ) then
    create policy "Fuvar olvasás engedélyezése"
    on public.fuvarok
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='fuvarok' and policyname='Fuvar módosítás adminnak'
  ) then
    create policy "Fuvar módosítás adminnak"
    on public.fuvarok
    for update
    to authenticated
    using (true)
    with check (true);
  end if;
end $$;

alter table if exists public.fuvarok add column if not exists sofor_ertekeles numeric default 4.9;



do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='fuvarok' and policyname='Fuvar törlés engedélyezése'
  ) then
    create policy "Fuvar törlés engedélyezése"
    on public.fuvarok
    for delete
    to authenticated
    using (true);
  end if;
end $$;


-- Fuvarok extra oszlopok
alter table if exists public.fuvarok add column if not exists auto_tipus text;
alter table if exists public.fuvarok add column if not exists bankszamla text;
alter table if exists public.fuvarok add column if not exists statusz text default 'Függőben';
alter table if exists public.fuvarok add column if not exists auto_helyek integer;
alter table if exists public.fuvarok add column if not exists osszes_hely integer;
alter table if exists public.fuvarok add column if not exists fizetesi_modok text[];
alter table if exists public.fuvarok add column if not exists sofor_ertekeles numeric default 5;
alter table if exists public.fuvarok add column if not exists user_id uuid;
alter table if exists public.fuvarok add column if not exists approved boolean default false;
alter table if exists public.fuvarok add column if not exists created_at timestamptz default now();
alter table if exists public.fuvarok add column if not exists updated_at timestamptz default now();

-- Foglalások oszlopok
alter table if exists public.foglalasok add column if not exists nev text;
alter table if exists public.foglalasok add column if not exists email text;
alter table if exists public.foglalasok add column if not exists telefon text;
alter table if exists public.foglalasok add column if not exists foglalt_helyek integer default 1;
alter table if exists public.foglalasok add column if not exists fizetesi_mod text;
alter table if exists public.foglalasok add column if not exists megjegyzes text;
alter table if exists public.foglalasok add column if not exists created_at timestamptz default now();

-- Értékelések
create table if not exists public.ertekelesek (
  id bigint generated by default as identity primary key,
  fuvar_id bigint,
  user_email text,
  user_name text,
  csillag integer check (csillag between 1 and 5),
  szoveg text,
  created_at timestamptz default now()
);

alter table if exists public.fuvarok enable row level security;
alter table if exists public.foglalasok enable row level security;
alter table if exists public.ertekelesek enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='fuvarok' and policyname='Fuvar beszúrás engedélyezése'
  ) then
    create policy "Fuvar beszúrás engedélyezése" on public.fuvarok
    for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='fuvarok' and policyname='Fuvar olvasás engedélyezése'
  ) then
    create policy "Fuvar olvasás engedélyezése" on public.fuvarok
    for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='fuvarok' and policyname='Fuvar módosítás adminnak'
  ) then
    create policy "Fuvar módosítás adminnak" on public.fuvarok
    for update to authenticated using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='fuvarok' and policyname='Fuvar törlés engedélyezése'
  ) then
    create policy "Fuvar törlés engedélyezése" on public.fuvarok
    for delete to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='foglalasok' and policyname='Foglalás beszúrás engedélyezése'
  ) then
    create policy "Foglalás beszúrás engedélyezése" on public.foglalasok
    for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='foglalasok' and policyname='Foglalás olvasás engedélyezése'
  ) then
    create policy "Foglalás olvasás engedélyezése" on public.foglalasok
    for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='ertekelesek' and policyname='Értékelés beszúrás engedélyezése'
  ) then
    create policy "Értékelés beszúrás engedélyezése" on public.ertekelesek
    for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='ertekelesek' and policyname='Értékelés olvasás engedélyezése'
  ) then
    create policy "Értékelés olvasás engedélyezése" on public.ertekelesek
    for select to anon, authenticated using (true);
  end if;
end $$;

create index if not exists idx_fuvarok_approved_created_at
on public.fuvarok (approved, created_at desc);

